// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SpMat_DescendingROI
arma::mat SpMat_DescendingROI(const arma::umat locations, const arma::vec values, const arma::uword rttol, const double ppm, const bool debugL, const bool eachiter);
RcppExport SEXP _ionshed_SpMat_DescendingROI(SEXP locationsSEXP, SEXP valuesSEXP, SEXP rttolSEXP, SEXP ppmSEXP, SEXP debugLSEXP, SEXP eachiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type rttol(rttolSEXP);
    Rcpp::traits::input_parameter< const double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< const bool >::type debugL(debugLSEXP);
    Rcpp::traits::input_parameter< const bool >::type eachiter(eachiterSEXP);
    rcpp_result_gen = Rcpp::wrap(SpMat_DescendingROI(locations, values, rttol, ppm, debugL, eachiter));
    return rcpp_result_gen;
END_RCPP
}
// SpMat_getEICs
Rcpp::DataFrame SpMat_getEICs(const arma::umat locations, const arma::dmat values, const arma::umat eics_dt, const arma::uword rttol, const bool debugL);
RcppExport SEXP _ionshed_SpMat_getEICs(SEXP locationsSEXP, SEXP valuesSEXP, SEXP eics_dtSEXP, SEXP rttolSEXP, SEXP debugLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< const arma::dmat >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::umat >::type eics_dt(eics_dtSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type rttol(rttolSEXP);
    Rcpp::traits::input_parameter< const bool >::type debugL(debugLSEXP);
    rcpp_result_gen = Rcpp::wrap(SpMat_getEICs(locations, values, eics_dt, rttol, debugL));
    return rcpp_result_gen;
END_RCPP
}
// summarize_one_class
Rcpp::DataFrame summarize_one_class(double roi, NumericVector rt_nv, NumericVector i_nv, NumericVector mz_nv, IntegerVector mzsc_iv, IntegerVector rtsc_iv);
RcppExport SEXP _ionshed_summarize_one_class(SEXP roiSEXP, SEXP rt_nvSEXP, SEXP i_nvSEXP, SEXP mz_nvSEXP, SEXP mzsc_ivSEXP, SEXP rtsc_ivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type roi(roiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rt_nv(rt_nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i_nv(i_nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mz_nv(mz_nvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mzsc_iv(mzsc_ivSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rtsc_iv(rtsc_ivSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_one_class(roi, rt_nv, i_nv, mz_nv, mzsc_iv, rtsc_iv));
    return rcpp_result_gen;
END_RCPP
}
// summarize_by_class
Rcpp::DataFrame summarize_by_class(DataFrame df, bool debugL);
RcppExport SEXP _ionshed_summarize_by_class(SEXP dfSEXP, SEXP debugLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< bool >::type debugL(debugLSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_by_class(df, debugL));
    return rcpp_result_gen;
END_RCPP
}
// min_diff
double min_diff(std::vector<double> mz_vec);
RcppExport SEXP _ionshed_min_diff(SEXP mz_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type mz_vec(mz_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(min_diff(mz_vec));
    return rcpp_result_gen;
END_RCPP
}
// min_diff_by_group
double min_diff_by_group(Rcpp::NumericVector in_vec, Rcpp::NumericVector group_vec);
RcppExport SEXP _ionshed_min_diff_by_group(SEXP in_vecSEXP, SEXP group_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type in_vec(in_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type group_vec(group_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(min_diff_by_group(in_vec, group_vec));
    return rcpp_result_gen;
END_RCPP
}
// zigzag_index
double zigzag_index(std::vector<double> intPts);
RcppExport SEXP _ionshed_zigzag_index(SEXP intPtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type intPts(intPtsSEXP);
    rcpp_result_gen = Rcpp::wrap(zigzag_index(intPts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ionshed_SpMat_DescendingROI", (DL_FUNC) &_ionshed_SpMat_DescendingROI, 6},
    {"_ionshed_SpMat_getEICs", (DL_FUNC) &_ionshed_SpMat_getEICs, 5},
    {"_ionshed_summarize_one_class", (DL_FUNC) &_ionshed_summarize_one_class, 6},
    {"_ionshed_summarize_by_class", (DL_FUNC) &_ionshed_summarize_by_class, 2},
    {"_ionshed_min_diff", (DL_FUNC) &_ionshed_min_diff, 1},
    {"_ionshed_min_diff_by_group", (DL_FUNC) &_ionshed_min_diff_by_group, 2},
    {"_ionshed_zigzag_index", (DL_FUNC) &_ionshed_zigzag_index, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ionshed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
