# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to attribute ROI by taking the highest intensity points
#'
#' This function returns a matrix with m/Z groups
#' based on a tolerance. This version is the final one.
#'
#' @param locations A matrix (2xN) with row (1xN) and column (1xN)
#' @param values A vector of N values
#' @param rttol Tolerance in rt dimension (grid points)
#' @param ppm Tolerance in ppm (variable grid)
#' @param debug Boolean to print debug messages
#' @param eachiter Boolean to return iteration steps details
#' @export
#'
SpMat_DescendingROI <- function(locations, values, rttol = 10L, ppm = 10, debug = FALSE, eachiter = FALSE) {
    .Call(`_ionshed_SpMat_DescendingROI`, locations, values, rttol, ppm, debug, eachiter)
}

#' Function to extract EIcs using Sparse Matrix
#'
#' This function returns a matrice with EICs corresponding to asked range(s).
#'
#' @param locations A matrix (2xN) with row (1xN) and column (1xN)
#' @param values A matrix (ValuesxN) with values in the same order as locations
#' @param eics_dt coordinate as a matrix with id, mzmin, mzmax, rtmin, rtmax
#' @param rttol (optional) to extend the rt range
#' @param debug Boolean to print debug message
#' @export
#'
SpMat_getEICs <- function(locations, values, eics_dt, rttol = 10L, debug = FALSE) {
    .Call(`_ionshed_SpMat_getEICs`, locations, values, eics_dt, rttol, debug)
}

summarize_one_class <- function(roi, rt_nv, i_nv, mz_nv, mzsc_iv, rtsc_iv) {
    .Call(`_ionshed_summarize_one_class`, roi, rt_nv, i_nv, mz_nv, mzsc_iv, rtsc_iv)
}

summarize_by_class <- function(df, debug = FALSE) {
    .Call(`_ionshed_summarize_by_class`, df, debug)
}

min_diff <- function(mz_vec) {
    .Call(`_ionshed_min_diff`, mz_vec)
}

min_diff_by_group <- function(in_vec, group_vec) {
    .Call(`_ionshed_min_diff_by_group`, in_vec, group_vec)
}

#' Function to compute the ZigZag index
#'
#' This function returns the ZigZag index as a numeric
#' value of a single trace.
#'
#' @param intPts Numeric vector of intensity pre-ordered by time
#' @export
#'
zigzag_index <- function(intPts) {
    .Call(`_ionshed_zigzag_index`, intPts)
}

